[package]
name = "skibidiscrap"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.23.0"
